### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [dfordivam/dfordivam.github.io#1]
Hi! I am the editor of [Haskell Weekly](https://haskellweekly.news). I would like to be notified when you write a new post, but as far as I can tell your blog does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by dfordivam** [comment]
Hello @tfausak I have added the atom.xml file to the blog.
And thanks again for your wonderful work!

**Comment by tfausak** [comment]
Thanks!
